### ISSUE TITLE
migrate away from fedora-34-4vcpu nodeset

### ISSUE THREAD

**Issue by pabelanger** [ansible/ansible-zuul-jobs#1034]
@jillr @tremble @goneri Can we migrate your jobs away from fedora-34-4vcpu?  This image only runs in aws, and we only have capacity to run 5 jobs at a time.

I would like to see it migrated to centos-8 nodesets, given we run them in many more providers.

Also, do your controller jobs really need 4vcpu? or can it be scaled down to 1vcpu / 2vcpu.

**Comment by tremble** [comment]
@pabelanger

WRT vCPUs, I don't see any reason each job would need 4 vCPUs only the unit tests have any signigicant level of parallelism.  Some tests run in parallel because the APIs they're talking to are slow, so dropping to 2 might be better than 1, but I can't imagine 4vCPUs is really needed.  The main thing we care about is the availability of Python (and access to publicly available AWS APIs)

I don't see where this is configured, but if you can point me in the right direction I can get some tests run through to validate things.

**Comment by jillr** [comment]
Yeah I think that should be fine too
@tremble should be in the job config at https://github.com/ansible/ansible-zuul-jobs/blob/master/zuul.d/ansible-cloud-jobs.yaml#L282 
and I believe that would change to   nodeset: centos-8-1vcpu
or maybe centos-8-stream?

**Comment by goneri** [comment]
Hi Paul and all,

The fedora-34-4vcpu nodeset was a request from @abikouo . He was looking
for a flavor able to run Molecule properly.

Overall, I think CentOS8 is now a dead-end nobody really use and the
versions in AWS and OpenStack are different enough to create problems.
Both side are drifting away because there is no more upstream.
And it's getting in our way when want to use stuff like podman.

I would personally prefer to use Fedora because it's easier to troubleshot
a problem when and the software stack is up to date.

I would also like to use their official cloud images to get a
reproducible environment. We already use them when the jobs run
on AWS and this would be a way to have a common ground.

**Comment by jillr** [comment]
Thanks for the background info @goneri that makes sense.  We don't need 4 cores for AWS though. I'm looking through the nodesets for another option, could we try fedora-latest-1vcpu?

**Comment by pabelanger** [comment]
we now have centos-8-stream images which I would like to migrate too. For fedora images, they really are only 6 month support which makes them really fast to change out.  Give we want to push up more platform level testing, it's difficult to support stuff on multiple distros.

Is there something specific fedora gets us, that centos-8-stream doesn;t?

**Comment by goneri** [comment]
> Thanks for the background info @goneri that makes sense. We don't need 4 cores for AWS though. I'm looking through the nodesets for another option, could we try fedora-latest-1vcpu?

The fedora-34-4vcpu label exists but nothing uses it.

**Comment by goneri** [comment]
> we now have centos-8-stream images which I would like to migrate too. For fedora images, they really are only 6 month support which makes them really fast to change out. Give we want to push up more platform level testing, it's difficult to support stuff on multiple distros.
> 
> Is there something specific fedora gets us, that centos-8-stream doesn;t?

We've got to support fedora anyway this is what we actually use for our development environment.

I don't mind using a different OS but I prefer to have something standard across AWS, OpenStack, a potential 3rd provider later or even Vagrant.

And to be sure the environment is reproducible I would prefer we use some official vendor supported cloud images. This image are standard across the different providers and this simplifies the troubleshooting for our contributors. 

https://cloud.centos.org/centos/8-stream/x86_64/images/
https://www.centos.org/download/aws-images/

**Comment by pabelanger** [comment]
> > we now have centos-8-stream images which I would like to migrate too. For fedora images, they really are only 6 month support which makes them really fast to change out. Give we want to push up more platform level testing, it's difficult to support stuff on multiple distros.
> > Is there something specific fedora gets us, that centos-8-stream doesn;t?
> 
> We've got to support fedora anyway this is what we actually use for our development environment.
> 
> I don't mind using a different OS but I prefer to have something standard across AWS, OpenStack, a potential 3rd provider later or even Vagrant.
> 
> And to be sure the environment is reproducible I would prefer we use some official vendor supported cloud images. This image are standard across the different providers and this simplifies the troubleshooting for our contributors.
> 
> [cloud.centos.org/centos/8-stream/x86_64/images](https://cloud.centos.org/centos/8-stream/x86_64/images/)
> [centos.org/download/aws-images](https://www.centos.org/download/aws-images/)

Realistically, these images are not going to happen any time soon.  That doesn't mean someone cannot take up the effort to do it, but given today openstack clouds are built using DIB, and we properly sync all step 0 is getting amazon aws to support this too.

The main idea of using centos-8-stream (or something other then fedora) is to limit the difference between aws jobs via all other collections.  Given last week there were 2 people on PTO, it was a large uptick for me to understand the jobs.

Additionally, if we are trying to push upstream some downstream testing there is value in using centos-8-stream too, it potentially means less work for you and your team to get downstream working.

For this to really happen, we need to land https://review.opendev.org/c/zuul/zuul/+/775042 upstream IMO. Until that happens, I would say any changes to our images would be a -1 from me.  We just don't have the automation in place to deal with it yet.

**Comment by jillr** [comment]
@pabelanger How does the centos-8-stream image currently in our zuul differ from the CentOS maintained images on, for example, public cloud?  (or does it differ at all?)  Does our centos-8-stream image support molecule and podman?  Basically I'm asking, based on the conversation here, does this image satisfy the requests/requirements that the cloud team has?

Goneri and I were on PTO last week but Aubin was around as our CI Vanguard.  This is a new role we've adopted but we'll always have someone in this role going forward.  We should never need to block on any one person that way.

**Comment by pabelanger** [comment]
The images we have in zuul, are in fact the same as upstream 'cloud-images', except we produce them from scratch ourself. In the original days of openstack-infra, we did infact do what is being asked now, consume cloud images upstream however we learned fast that upstream would just delete them randomly making it difficult to keep online.

Things likely have changed in the last 5-7 years but to go back to that process would be a large task. Using the centos-8-stream image now, will be fine. We have various jobs today for network integration that are using them with / without podman and do not have issues.

This nodeset is also using new flavors in our clouds, which should be faster then previous nodesets.  For the sake of simplifying our image management I'm asking we first try centos-8-stream for your jobs, and if they work great.

As for each public cloud providing an image to consume, they too are often tainted with per site changes, which is another reason we build the image once and upload every place.

**Comment by pabelanger** [comment]
Both https://dashboard.zuul.ansible.com/t/ansible/build/b2b173a78ae9414f88af689dd26f1702 and https://dashboard.zuul.ansible.com/t/ansible/build/8e69f60f0bcc478f93b0b36e57376c9a are centos-8-stream jobs, for amazon.aws using podman. There should not be an issue running molecule under python38.

**Comment by goneri** [comment]
There is no fedora-34-4vcpu anymore: https://github.com/ansible-network/windmill-config/pull/882
