### ISSUE TITLE
ansible-test-sanity-docker jobs TIME_OUT

### ISSUE THREAD

**Issue by goneri** [ansible/ansible-zuul-jobs#1190]
sanity tests often fail during `/usr/bin/python3.8 -m rstcheck --report warning --ignore-substitutions _,br,release,today,version CHANGELOG.rst`

e.g: https://36a2412fb528f2268b0e-ca3223f8735de702b39597abafa0b0a3.ssl.cf2.rackcdn.com/93/a0740c2b2784cbd0dee4e6166500b899381767b2/check/ansible-test-sanity-docker-stable-2.10/d8c9751/job-output.txt

**Comment by GomathiselviS** [comment]
@goneri This issue is seen here https://dashboard.zuul.ansible.com/t/ansible/build/fed0dbf69c474841a71106bb053add72

**Comment by goneri** [comment]
The two logs are from jobs with ansible-2.10.
