### ISSUE TITLE
need podman and docker roles

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible-zuul-jobs#294]
Molecule tox jobs may need docker-ce and/or podman installed, we need some roles we can add to enable them. I will try to use the roles from upstream zuul-jobs.

PS. Assign it to me

**Comment by pabelanger** [comment]
Yah, we should be able to do this using zuul-jobs upstream. So far, no projects really have been using them. So happy to see this work.

We likely want to add something like zuul-registry to we can also do speculative container builds.

**Comment by ssbarnea** [comment]
closing for the moment as we sorted it, at least locally.
