### ISSUE TITLE
fedora-30 nodeset used for tox py27 jobs does not have python2-libselinux

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible-zuul-jobs#316]
Currently tox 27 jobs are using a fedora-30 node but they miss the python2-libselinux package which is critical for some Ansible modules, mainly blocking testing molecule.

I cannot put `python2-libselinux` inside bindep because is a conditional dependency, it is needed only for the python version that you are using.

Thus I think we need to be sure that when we setup tox nodesets we need to double-check that selinux bindings are also installed. As you know that is one library that cannot be compiled by pip.

**Comment by pabelanger** [comment]
python27 jobs now are centos-7 only, as we move to fedora-31 and fedora-32, python is getting dropped. There also isn't a python2-libselinux package on fedora now, if I remember right.

**Comment by ssbarnea** [comment]
py27 with centos-7 seems like a good combination to use for old-baseline support. The libselinux situation improved after I raised few bugzilla tickets and we are expected to see them in all shipping python versions in the future. Still, I do not see much value for other platforms.
