### ISSUE TITLE
fedora-32 nodeset missing, needed for py38

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible-zuul-jobs#445]
Apparently we are missing fedora-32 nodepool image, which is a real deal because it woud have sorted the missing py38 testing environment. 

For example any jobs in `tox-py38` category would fail because there is no python3.8 installed on any of the nodes.

If we enable fedora-32, we can change the tox jobs to point to it and cover this python version too.

**Comment by goneri** [comment]
Closing, use either a fedora-34 or a fedora-35 node.

**Comment by goneri** [comment]
:-), I was doing some house keeping.
